# Copyright (c) Saviynt Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.1.0
info:
  description: |
    API for managing entitlements in Saviynt/SSM.
    - **Create Entitlement**: Creates a new entitlement.
    - **Update Entitlement**: Updates an existing entitlement.
    - **Get Entitlement List**: Returns a list of entitlement based on search criteria.
  title: Entitlement Management API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  /ECM/api/v5/createUpdateEntitlement:
    post:
      operationId: createUpdateEntitlement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUpdateEntitlementRequest"
        description: Request payload for creating/updating an entitlement
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrUpdateEntitlementResponse"
          description: Create/Update entitlement success
          headers:
            Access-Control-Allow-Credentials:
              explode: false
              schema:
                example: "true"
                type: string
              style: simple
            Access-Control-Allow-Origin:
              explode: false
              schema:
                example: http://localhost
                type: string
              style: simple
            Cache-Control:
              explode: false
              schema:
                example: "no-store, no-cache, must-revalidate"
                type: string
              style: simple
            Date:
              explode: false
              schema:
                example: "Wed, 08 Aug 2018 00:33:37 GMT"
                type: string
              style: simple
      summary: Create and update an entitlement
      tags:
      - entitlement
  /ECM/api/v5/getEntitlements:
    post:
      operationId: getEntitlements
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetEntitlementRequest"
        description: Request payload for getting a list of entitlements
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEntitlementResponse"
          description: Get entitlements success
          headers:
            Access-Control-Allow-Credentials:
              explode: false
              schema:
                example: "true"
                type: string
              style: simple
            Access-Control-Allow-Origin:
              explode: false
              schema:
                example: http://localhost
                type: string
              style: simple
            Cache-Control:
              explode: false
              schema:
                example: "no-store, no-cache, must-revalidate"
                type: string
              style: simple
            Date:
              explode: false
              schema:
                example: "Wed, 08 Aug 2018 00:33:37 GMT"
                type: string
              style: simple
      summary: Get list of entitlements
      tags:
      - entitlement
components:
  schemas:
    CreateUpdateEntitlementRequest:
      example:
        customproperty10: customproperty10
        entitlementowner26:
        - entitlementowner26
        - entitlementowner26
        entitlementowner27:
        - entitlementowner27
        - entitlementowner27
        customproperty12: customproperty12
        entitlementowner24:
        - entitlementowner24
        - entitlementowner24
        customproperty11: customproperty11
        entitlementowner25:
        - entitlementowner25
        - entitlementowner25
        customproperty18: customproperty18
        customproperty17: customproperty17
        customproperty19: customproperty19
        customproperty14: customproperty14
        entitlementowner22:
        - entitlementowner22
        - entitlementowner22
        customproperty13: customproperty13
        entitlementowner23:
        - entitlementowner23
        - entitlementowner23
        customproperty16: customproperty16
        entitlementowner20:
        - entitlementowner20
        - entitlementowner20
        entitlement_glossary: entitlement_glossary
        customproperty15: customproperty15
        entitlementowner21:
        - entitlementowner21
        - entitlementowner21
        entitlement_value: sample-entitlement-value
        entitlementowner15:
        - entitlementowner15
        - entitlementowner15
        entitlementowner16:
        - entitlementowner16
        - entitlementowner16
        entitlementowner13:
        - entitlementowner13
        - entitlementowner13
        entitlementowner14:
        - entitlementowner14
        - entitlementowner14
        entitlementowner19:
        - entitlementowner19
        - entitlementowner19
        entitlementowner17:
        - entitlementowner17
        - entitlementowner17
        module: module
        customproperty40: customproperty40
        entitlementowner18:
        - entitlementowner18
        - entitlementowner18
        priviliged: 5
        priority: 2
        entitlementowner11:
        - entitlementowner11
        - entitlementowner11
        entitlementowner12:
        - entitlementowner12
        - entitlementowner12
        entitlementowner10:
        - entitlementowner10
        - entitlementowner10
        entitlementmap:
        - endpoint: endpoint
          requestfilter: true
          excludeentitlement: excludeentitlement
          adddependenttask: adddependenttask
          removedependententtask: removedependententtask
          entitlementtype: entitlementtype
          entitlementvalue: entitlementvalue
          updateType: ADD
        - endpoint: endpoint
          requestfilter: true
          excludeentitlement: excludeentitlement
          adddependenttask: adddependenttask
          removedependententtask: removedependententtask
          entitlementtype: entitlementtype
          entitlementvalue: entitlementvalue
          updateType: ADD
        soxcritical: 1
        status: 6
        customproperty4: customproperty4
        customproperty32: customproperty32
        customproperty5: customproperty5
        customproperty31: customproperty31
        customproperty2: customproperty2
        customproperty34: customproperty34
        access: access
        customproperty3: customproperty3
        customproperty33: customproperty33
        customproperty1: customproperty1
        customproperty30: customproperty30
        confidentiality: 7
        description: description
        customproperty39: customproperty39
        customproperty36: customproperty36
        customproperty35: customproperty35
        customproperty38: customproperty38
        customproperty37: customproperty37
        endpoint: sample-endpoint
        entitlementcasecheck: false
        customproperty8: customproperty8
        customproperty9: customproperty9
        entitlementtype: sample-entitlement-type
        customproperty6: customproperty6
        customproperty7: customproperty7
        syscritical: 5
        customproperty21: customproperty21
        customproperty20: customproperty20
        customproperty23: customproperty23
        customproperty22: customproperty22
        entitlement_valuekey: entitlement_valuekey
        entitlementID: entitlementID
        customproperty29: customproperty29
        entitlementowner2:
        - entitlementowner2
        - entitlementowner2
        customproperty28: customproperty28
        entitlementowner3:
        - entitlementowner3
        - entitlementowner3
        newentitlement_value: newentitlement_value
        entitlementowner4:
        - entitlementowner4
        - entitlementowner4
        entitlementowner5:
        - entitlementowner5
        - entitlementowner5
        updatedentitlement_value: updatedentitlement_value
        customproperty25: customproperty25
        customproperty24: customproperty24
        customproperty27: customproperty27
        customproperty26: customproperty26
        entitlementowner1:
        - entitlementowner1
        - entitlementowner1
        entitlementowner6:
        - entitlementowner6
        - entitlementowner6
        entitlementowner7:
        - entitlementowner7
        - entitlementowner7
        entitlementowner8:
        - entitlementowner8
        - entitlementowner8
        displayname: displayname
        entitlementowner9:
        - entitlementowner9
        - entitlementowner9
        attributes: attributes
        risk: 0
      properties:
        endpoint:
          description: Name of the endpoint for the entitlement
          example: sample-endpoint
          type: string
        entitlementtype:
          description: Entitlement type for the entitlement
          example: sample-entitlement-type
          type: string
        entitlement_value:
          description: Value of the entitlement
          example: sample-entitlement-value
          type: string
        attributes:
          description: Attributes for entitlement values
          type: string
        entitlementID:
          description: Unique identifier for entitlement. Used to update the entitlement
            if multiple entitlements with same entitlement_value are present under
            the same entitlementtype and endpoint.
          type: string
        newentitlement_value:
          description: New value for the entitlement if updating an existing one
          type: string
        entitlementcasecheck:
          description: "If true, entitlement value search will be case sensitive during\
            \ create or update."
          example: false
          type: string
        entitlement_valuekey:
          description: Key for the entitlement value
          type: string
        updatedentitlement_value:
          description: New value for entitlement_value
          type: string
        displayname:
          description: Display name of the entitlement.
          type: string
        risk:
          description: Indicates the risk score or level of the entitlement.
          type: integer
        status:
          description: "Status of the entitlement (e.g., active/inactive)."
          type: integer
        soxcritical:
          description: SOX criticality flag.
          type: integer
        syscritical:
          description: System criticality flag.
          type: integer
        entitlement_glossary:
          description: Glossary term or explanation for the entitlement.
          type: string
        priviliged:
          description: Indicates if the entitlement is privileged.
          type: integer
        module:
          description: Functional module the entitlement belongs to.
          type: string
        access:
          description: "Access type or permission level (e.g., Read-Only)."
          type: string
        priority:
          description: Priority level of the entitlement.
          type: integer
        description:
          description: Description of the entitlement.
          type: string
        confidentiality:
          description: Confidentiality classification level.
          type: integer
        customproperty1:
          description: Custom property 1 value.
          type: string
        customproperty2:
          description: Custom property 2 value.
          type: string
        customproperty3:
          description: Custom property 3 value.
          type: string
        customproperty4:
          description: Custom property 4 value.
          type: string
        customproperty5:
          description: Custom property 5 value.
          type: string
        customproperty6:
          description: Custom property 6 value.
          type: string
        customproperty7:
          description: Custom property 7 value.
          type: string
        customproperty8:
          description: Custom property 8 value.
          type: string
        customproperty9:
          description: Custom property 9 value.
          type: string
        customproperty10:
          description: Custom property 10 value.
          type: string
        customproperty11:
          description: Custom property 11 value.
          type: string
        customproperty12:
          description: Custom property 12 value.
          type: string
        customproperty13:
          description: Custom property 13 value.
          type: string
        customproperty14:
          description: Custom property 14 value.
          type: string
        customproperty15:
          description: Custom property 15 value.
          type: string
        customproperty16:
          description: Custom property 16 value.
          type: string
        customproperty17:
          description: Custom property 17 value.
          type: string
        customproperty18:
          description: Custom property 18 value.
          type: string
        customproperty19:
          description: Custom property 19 value.
          type: string
        customproperty20:
          description: Custom property 20 value.
          type: string
        customproperty21:
          description: Custom property 21 value.
          type: string
        customproperty22:
          description: Custom property 22 value.
          type: string
        customproperty23:
          description: Custom property 23 value.
          type: string
        customproperty24:
          description: Custom property 24 value.
          type: string
        customproperty25:
          description: Custom property 25 value.
          type: string
        customproperty26:
          description: Custom property 26 value.
          type: string
        customproperty27:
          description: Custom property 27 value.
          type: string
        customproperty28:
          description: Custom property 28 value.
          type: string
        customproperty29:
          description: Custom property 29 value.
          type: string
        customproperty30:
          description: Custom property 30 value.
          type: string
        customproperty31:
          description: Custom property 31 value.
          type: string
        customproperty32:
          description: Custom property 32 value.
          type: string
        customproperty33:
          description: Custom property 33 value.
          type: string
        customproperty34:
          description: Custom property 34 value.
          type: string
        customproperty35:
          description: Custom property 35 value.
          type: string
        customproperty36:
          description: Custom property 36 value.
          type: string
        customproperty37:
          description: Custom property 37 value.
          type: string
        customproperty38:
          description: Custom property 38 value.
          type: string
        customproperty39:
          description: Custom property 39 value.
          type: string
        customproperty40:
          description: Custom property 40 value.
          type: string
        entitlementowner1:
          description: Primary entitlement owners.
          items:
            type: string
          type: array
        entitlementowner2:
          description: Secondary entitlement owners.
          items:
            type: string
          type: array
        entitlementowner3:
          items:
            type: string
          type: array
        entitlementowner4:
          items:
            type: string
          type: array
        entitlementowner5:
          items:
            type: string
          type: array
        entitlementowner6:
          items:
            type: string
          type: array
        entitlementowner7:
          items:
            type: string
          type: array
        entitlementowner8:
          items:
            type: string
          type: array
        entitlementowner9:
          items:
            type: string
          type: array
        entitlementowner10:
          items:
            type: string
          type: array
        entitlementowner11:
          items:
            type: string
          type: array
        entitlementowner12:
          items:
            type: string
          type: array
        entitlementowner13:
          items:
            type: string
          type: array
        entitlementowner14:
          items:
            type: string
          type: array
        entitlementowner15:
          items:
            type: string
          type: array
        entitlementowner16:
          items:
            type: string
          type: array
        entitlementowner17:
          items:
            type: string
          type: array
        entitlementowner18:
          items:
            type: string
          type: array
        entitlementowner19:
          items:
            type: string
          type: array
        entitlementowner20:
          items:
            type: string
          type: array
        entitlementowner21:
          items:
            type: string
          type: array
        entitlementowner22:
          items:
            type: string
          type: array
        entitlementowner23:
          items:
            type: string
          type: array
        entitlementowner24:
          items:
            type: string
          type: array
        entitlementowner25:
          items:
            type: string
          type: array
        entitlementowner26:
          items:
            type: string
          type: array
        entitlementowner27:
          items:
            type: string
          type: array
        entitlementmap:
          items:
            $ref: "#/components/schemas/CreateUpdateEntitlementRequest_entitlementmap_inner"
          type: array
      required:
      - endpoint
      - entitlement_value
      - entitlementtype
    GetEntitlementResponse:
      example:
        msg: Successful
        Entitlementdetails:
        - createdate: createdate
          entitlement_glossary: entitlement_glossary
          updatedate: updatedate
          Test Support: cp3
          entitlement_value: entitlement_value
          module: module
          customproperty40: customproperty40
          priviliged: priviliged
          childEntitlementCount: 6
          entitlementType: entitlementType
          priority: priority
          soxcritical: soxcritical
          status: status
          customproperty32: customproperty32
          customproperty31: customproperty31
          customproperty34: customproperty34
          access: access
          customproperty33: customproperty33
          endpointKey: 1
          customproperty30: customproperty30
          confidentiality: confidentiality
          description: description
          customproperty39: customproperty39
          customproperty36: customproperty36
          customproperty35: customproperty35
          customproperty38: customproperty38
          customproperty37: customproperty37
          endpoint: endpoint
          Custom Property 10: Custom Property 10
          Custom Property 11: Custom Property 11
          Custom Property 12: Custom Property 12
          Custom Property 13: Custom Property 13
          Custom Property 14: Custom Property 14
          syscritical: syscritical
          Custom Property 4: Custom Property 4
          Custom Property 15: Custom Property 15
          customproperty21: customproperty21
          Custom Property 5: Custom Property 5
          Custom Property 16: Custom Property 16
          Custom Property 6: Custom Property 6
          Custom Property 17: Custom Property 17
          customproperty23: customproperty23
          Custom Property 7: Custom Property 7
          Custom Property 18: Custom Property 18
          customproperty22: customproperty22
          entitlementMapDetails:
          - primaryEntType: S1_2
            addDependentTask: true
            removeDependentEntTask: true
            excludeEntitlement: true
            description: testingParent
            exportPrimary: SS1_2
            requestFilter: true
            primary: SS1_2
            primaryEntKey: "2"
          - primaryEntType: S1_2
            addDependentTask: true
            removeDependentEntTask: true
            excludeEntitlement: true
            description: testingParent
            exportPrimary: SS1_2
            requestFilter: true
            primary: SS1_2
            primaryEntKey: "2"
          entitlement_valuekey: entitlement_valuekey
          Custom Property 8: Custom Property 8
          Custom Property 19: Custom Property 19
          Custom Property 9: Custom Property 9
          entitlementID: entitlementID
          customproperty29: customproperty29
          entitlementOwner:
          - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
          - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
          customproperty28: customproperty28
          entitlementTypeName: entitlementTypeName
          customproperty25: customproperty25
          Custom Property 1: Custom Property 1
          customproperty24: customproperty24
          Custom Property 2: Custom Property 2
          customproperty27: customproperty27
          Custom Property 3: Custom Property 3
          customproperty26: customproperty26
          entitlementTypeKey: 0
          requestForm: requestForm
          displayname: displayname
          risk: risk
          Custom Property 20: Custom Property 20
          accounts:
          - enddate: enddate
            accountname: accountname
            updatedate: updatedate
            startdate: startdate
          - enddate: enddate
            accountname: accountname
            updatedate: updatedate
            startdate: startdate
          updateuser: updateuser
        - createdate: createdate
          entitlement_glossary: entitlement_glossary
          updatedate: updatedate
          Test Support: cp3
          entitlement_value: entitlement_value
          module: module
          customproperty40: customproperty40
          priviliged: priviliged
          childEntitlementCount: 6
          entitlementType: entitlementType
          priority: priority
          soxcritical: soxcritical
          status: status
          customproperty32: customproperty32
          customproperty31: customproperty31
          customproperty34: customproperty34
          access: access
          customproperty33: customproperty33
          endpointKey: 1
          customproperty30: customproperty30
          confidentiality: confidentiality
          description: description
          customproperty39: customproperty39
          customproperty36: customproperty36
          customproperty35: customproperty35
          customproperty38: customproperty38
          customproperty37: customproperty37
          endpoint: endpoint
          Custom Property 10: Custom Property 10
          Custom Property 11: Custom Property 11
          Custom Property 12: Custom Property 12
          Custom Property 13: Custom Property 13
          Custom Property 14: Custom Property 14
          syscritical: syscritical
          Custom Property 4: Custom Property 4
          Custom Property 15: Custom Property 15
          customproperty21: customproperty21
          Custom Property 5: Custom Property 5
          Custom Property 16: Custom Property 16
          Custom Property 6: Custom Property 6
          Custom Property 17: Custom Property 17
          customproperty23: customproperty23
          Custom Property 7: Custom Property 7
          Custom Property 18: Custom Property 18
          customproperty22: customproperty22
          entitlementMapDetails:
          - primaryEntType: S1_2
            addDependentTask: true
            removeDependentEntTask: true
            excludeEntitlement: true
            description: testingParent
            exportPrimary: SS1_2
            requestFilter: true
            primary: SS1_2
            primaryEntKey: "2"
          - primaryEntType: S1_2
            addDependentTask: true
            removeDependentEntTask: true
            excludeEntitlement: true
            description: testingParent
            exportPrimary: SS1_2
            requestFilter: true
            primary: SS1_2
            primaryEntKey: "2"
          entitlement_valuekey: entitlement_valuekey
          Custom Property 8: Custom Property 8
          Custom Property 19: Custom Property 19
          Custom Property 9: Custom Property 9
          entitlementID: entitlementID
          customproperty29: customproperty29
          entitlementOwner:
          - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
          - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
          customproperty28: customproperty28
          entitlementTypeName: entitlementTypeName
          customproperty25: customproperty25
          Custom Property 1: Custom Property 1
          customproperty24: customproperty24
          Custom Property 2: Custom Property 2
          customproperty27: customproperty27
          Custom Property 3: Custom Property 3
          customproperty26: customproperty26
          entitlementTypeKey: 0
          requestForm: requestForm
          displayname: displayname
          risk: risk
          Custom Property 20: Custom Property 20
          accounts:
          - enddate: enddate
            accountname: accountname
            updatedate: updatedate
            startdate: startdate
          - enddate: enddate
            accountname: accountname
            updatedate: updatedate
            startdate: startdate
          updateuser: updateuser
        totalEntitlementCount: 1
        entitlementsCount: 1
        errorCode: "0"
      properties:
        msg:
          description: Response message indicating the result of the request.
          example: Successful
          type: string
        errorCode:
          description: Error code (0 for success).
          example: "0"
          type: string
        totalEntitlementCount:
          description: Total number of entitlements in the system.
          example: 1
          type: integer
        entitlementsCount:
          description: Number of entitlements returned in the response.
          example: 1
          type: integer
        Entitlementdetails:
          description: List of entitlements with full metadata.
          items:
            $ref: "#/components/schemas/GetEntitlementResponse_Entitlementdetails_inner"
          type: array
    CreateOrUpdateEntitlementResponse:
      example:
        msg: Successful in saving entitlement map
        entitlementObj:
          customproperty10: customproperty10
          customproperty12: customproperty12
          customproperty11: customproperty11
          customproperty18: customproperty18
          customproperty17: customproperty17
          createdate: 2025-09-02 05:04:19
          customproperty19: customproperty19
          customproperty14: customproperty14
          customproperty13: customproperty13
          customproperty16: customproperty16
          customproperty15: customproperty15
          entitlement_glossary: hello
          updatedate: 2025-09-02 06:06:00
          entitlement_value: postman_ent_1
          customproperty40: customproperty40
          module: IT
          priviliged: "0"
          entitlementType: ui_ent_type_1
          priority: "23"
          soxcritical: "6"
          status: "6"
          customproperty4: customproperty4
          customproperty32: customproperty32
          customproperty5: customproperty5
          customproperty31: customproperty31
          customproperty2: customproperty2
          customproperty34: customproperty34
          access: Delete
          customproperty3: cp3
          customproperty33: customproperty33
          customproperty1: cp1
          customproperty30: customproperty30
          endpointKey: 25307
          confidentiality: "3"
          customproperty39: customproperty39
          description: description for postman_ent_1
          customproperty36: customproperty36
          customproperty35: customproperty35
          customproperty38: customproperty38
          customproperty37: customproperty37
          endpoint: sample-101
          customproperty8: customproperty8
          customproperty9: customproperty9
          customproperty6: customproperty6
          customproperty7: customproperty7
          customproperty21: cp21
          syscritical: "3"
          customproperty20: cp20
          customproperty23: customproperty23
          customproperty22: customproperty22
          entitlement_valuekey: "8609642"
          customproperty29: customproperty29
          customproperty28: customproperty28
          entitlementOwner:
            Rank 200:
            - Saviynt_Training_User
            Rank 201:
            - Saviynt_Training_User
          entitlementTypeName: ui_ent_type_1
          customproperty25: customproperty25
          customproperty24: customproperty24
          customproperty27: customproperty27
          customproperty26: customproperty26
          entitlementTypeKey: 28846
          requestForm: Request Form Table
          displayname: display name for postman_ent_1
          risk: "4"
          updateuser: "109809"
        errorCode: "0"
      properties:
        msg:
          description: Response message indicating the result of the request.
          example: Successful in saving entitlement map
          type: string
        errorCode:
          description: Error code (0 for success).
          example: "0"
          type: string
        entitlementObj:
          $ref: "#/components/schemas/CreateOrUpdateEntitlementResponse_entitlementObj"
    GetEntitlementRequest:
      example:
        returnentitlementmap: "true"
        offset: 6
        max: 0
        exactmatch: "true"
        requestedObject: users
        entownerwithrank: "true"
        endpoint: endpoint
        entitlementResponseFields: entitlementResponseFields
        accountname: accountname
        entitlementfiltercriteria: entitlementfiltercriteria
        userfiltercriteria: userfiltercriteria
        entitlement_value: entitlement_value
        entitlementtype: entitlementtype
        userResponseFields: userResponseFields
        username: username
        entQuery: entQuery
      properties:
        username:
          description: Username to filter entitlements
          type: string
        entitlementtype:
          description: Type of entitlement to filter
          type: string
        entitlement_value:
          description: Entitlement value
          type: string
        endpoint:
          description: Name of the endpoint to filter entitlements
          type: string
        requestedObject:
          description: Type of object requested
          enum:
          - users
          - userscount
          type: string
        max:
          description: Maximum number of results to return
          type: integer
        offset:
          description: Number of results to skip
          type: integer
        entitlementResponseFields:
          description: Comma-separated list of entitlement fields to return
          type: string
        userResponseFields:
          description: Comma-separated list of user fields to return
          type: string
        userfiltercriteria:
          description: Filter criteria for users
          type: string
        accountname:
          description: Account name to filter by
          type: string
        entownerwithrank:
          description: "If \"true\", returns the list of owners with owner rank for\
            \ every entitlementValue"
          enum:
          - "true"
          - "false"
          type: string
        returnentitlementmap:
          description: "If true, entitlementmap details will be returned (default\
            \ is false)"
          enum:
          - "true"
          - "false"
          type: string
        exactmatch:
          description: "Default is true. If given as false, it will search based on\
            \ similar matches"
          enum:
          - "true"
          - "false"
          type: string
        entitlementfiltercriteria:
          description: Filter criteria for entitlements
          type: string
        entQuery:
          description: Query to support only entitlement_values parameters. Sample
            - "ent.description = 'Desc' or ent.displayname like '%display%'"
          type: string
    CreateUpdateEntitlementRequest_entitlementmap_inner:
      example:
        endpoint: endpoint
        requestfilter: true
        excludeentitlement: excludeentitlement
        adddependenttask: adddependenttask
        removedependententtask: removedependententtask
        entitlementtype: entitlementtype
        entitlementvalue: entitlementvalue
        updateType: ADD
      properties:
        entitlementvalue:
          description: Value of the entitlement
          type: string
        entitlementtype:
          description: Type of the entitlement
          type: string
        endpoint:
          description: Endpoint name
          type: string
        requestfilter:
          description: Request filter flag
          type: boolean
        excludeentitlement:
          description: Exclude entitlement flag
          type: string
        adddependenttask:
          description: Add dependent task flag
          type: string
        removedependententtask:
          description: Remove dependent entitlement task flag
          type: string
        updateType:
          description: "Update type (ADD, REMOVE, etc.)"
          enum:
          - ADD
          - REMOVE
          type: string
    GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner:
      oneOf:
      - description: List of usernames that own this entitlement.
        items:
          type: string
        type: array
      - additionalProperties:
          items:
            type: string
        description: Entitlement owners organized by rank(When `entownerwithrank`
          is set to true).
        example:
          Rank 1:
          - systemadmin
          - SaviyntSupportAgent1
          Rank 3:
          - test_non_admin
          - Saviynt_Training_User
      - description: Empty string when no owners are set.
        type: string
    GetEntitlementResponse_Entitlementdetails_inner_accounts_inner:
      example:
        enddate: enddate
        accountname: accountname
        updatedate: updatedate
        startdate: startdate
      properties:
        enddate:
          description: End date of the account association.
          type: string
        accountname:
          description: Name of the associated account.
          type: string
        updatedate:
          description: Update date of the account association.
          type: string
        startdate:
          description: Start date of the account association.
          type: string
    GetEntitlementResponse_Entitlementdetails_inner_entitlementMapDetails_inner:
      example:
        primaryEntType: S1_2
        addDependentTask: true
        removeDependentEntTask: true
        excludeEntitlement: true
        description: testingParent
        exportPrimary: SS1_2
        requestFilter: true
        primary: SS1_2
        primaryEntKey: "2"
      properties:
        primaryEntType:
          description: Type of the primary entitlement.
          example: S1_2
          type: string
        requestFilter:
          description: Request filter for the mapping.
          example: true
          type: boolean
        addDependentTask:
          description: Task to add dependent entitlement.
          example: true
          type: boolean
        removeDependentEntTask:
          description: Task to remove dependent entitlement.
          example: true
          type: boolean
        excludeEntitlement:
          description: Entitlements to exclude.
          example: true
          type: boolean
        primary:
          description: Primary entitlement identifier.
          example: SS1_2
          type: string
        primaryEntKey:
          description: Key of the primary entitlement.
          example: "2"
          type: string
        exportPrimary:
          description: Export identifier for primary entitlement.
          example: SS1_2
          type: string
        description:
          description: Description of the entitlement mapping.
          example: testingParent
          type: string
    GetEntitlementResponse_Entitlementdetails_inner:
      example:
        createdate: createdate
        entitlement_glossary: entitlement_glossary
        updatedate: updatedate
        Test Support: cp3
        entitlement_value: entitlement_value
        module: module
        customproperty40: customproperty40
        priviliged: priviliged
        childEntitlementCount: 6
        entitlementType: entitlementType
        priority: priority
        soxcritical: soxcritical
        status: status
        customproperty32: customproperty32
        customproperty31: customproperty31
        customproperty34: customproperty34
        access: access
        customproperty33: customproperty33
        endpointKey: 1
        customproperty30: customproperty30
        confidentiality: confidentiality
        description: description
        customproperty39: customproperty39
        customproperty36: customproperty36
        customproperty35: customproperty35
        customproperty38: customproperty38
        customproperty37: customproperty37
        endpoint: endpoint
        Custom Property 10: Custom Property 10
        Custom Property 11: Custom Property 11
        Custom Property 12: Custom Property 12
        Custom Property 13: Custom Property 13
        Custom Property 14: Custom Property 14
        syscritical: syscritical
        Custom Property 4: Custom Property 4
        Custom Property 15: Custom Property 15
        customproperty21: customproperty21
        Custom Property 5: Custom Property 5
        Custom Property 16: Custom Property 16
        Custom Property 6: Custom Property 6
        Custom Property 17: Custom Property 17
        customproperty23: customproperty23
        Custom Property 7: Custom Property 7
        Custom Property 18: Custom Property 18
        customproperty22: customproperty22
        entitlementMapDetails:
        - primaryEntType: S1_2
          addDependentTask: true
          removeDependentEntTask: true
          excludeEntitlement: true
          description: testingParent
          exportPrimary: SS1_2
          requestFilter: true
          primary: SS1_2
          primaryEntKey: "2"
        - primaryEntType: S1_2
          addDependentTask: true
          removeDependentEntTask: true
          excludeEntitlement: true
          description: testingParent
          exportPrimary: SS1_2
          requestFilter: true
          primary: SS1_2
          primaryEntKey: "2"
        entitlement_valuekey: entitlement_valuekey
        Custom Property 8: Custom Property 8
        Custom Property 19: Custom Property 19
        Custom Property 9: Custom Property 9
        entitlementID: entitlementID
        customproperty29: customproperty29
        entitlementOwner:
        - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
        - GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner
        customproperty28: customproperty28
        entitlementTypeName: entitlementTypeName
        customproperty25: customproperty25
        Custom Property 1: Custom Property 1
        customproperty24: customproperty24
        Custom Property 2: Custom Property 2
        customproperty27: customproperty27
        Custom Property 3: Custom Property 3
        customproperty26: customproperty26
        entitlementTypeKey: 0
        requestForm: requestForm
        displayname: displayname
        risk: risk
        Custom Property 20: Custom Property 20
        accounts:
        - enddate: enddate
          accountname: accountname
          updatedate: updatedate
          startdate: startdate
        - enddate: enddate
          accountname: accountname
          updatedate: updatedate
          startdate: startdate
        updateuser: updateuser
      properties:
        createdate:
          description: Timestamp when the entitlement was created.
          type: string
        updatedate:
          description: Timestamp when the entitlement was last updated.
          type: string
        entitlement_glossary:
          description: Glossary term or explanation for the entitlement.
          type: string
        entitlement_value:
          description: Unique identifier or value of the entitlement.
          type: string
        entitlement_valuekey:
          description: Key corresponding to the entitlement value.
          type: string
        entitlementID:
          description: Display ID of the entitlement.
          type: string
        entitlementType:
          description: Technical name of the entitlement type.
          type: string
        entitlementTypeName:
          description: Display name of the entitlement type.
          type: string
        entitlementTypeKey:
          description: Unique key for the entitlement type.
          type: integer
        description:
          description: Description of the entitlement.
          type: string
        displayname:
          description: Display name of the entitlement.
          type: string
        module:
          description: Functional module the entitlement belongs to.
          type: string
        access:
          description: "Access type or permission level (e.g., Read-Only)."
          type: string
        risk:
          description: Indicates the risk score or level of the entitlement.
          type: string
        soxcritical:
          description: SOX criticality flag.
          type: string
        syscritical:
          description: System criticality flag.
          type: string
        confidentiality:
          description: Confidentiality classification level.
          type: string
        priority:
          description: Priority level of the entitlement.
          type: string
        priviliged:
          description: Indicates if the entitlement is privileged.
          type: string
        status:
          description: "Status of the entitlement (e.g., active/inactive)."
          type: string
        requestForm:
          description: Request form associated with this entitlement.
          type: string
        updateuser:
          description: User who last updated the entitlement.
          type: string
        childEntitlementCount:
          description: Number of child entitlements linked to this one.
          type: integer
        endpoint:
          description: Name of the endpoint the entitlement is linked to.
          type: string
        endpointKey:
          description: Key of the endpoint associated with the entitlement.
          type: integer
        entitlementOwner:
          $ref: "#/components/schemas/GetEntitlementResponse_Entitlementdetails_inner_entitlementOwner"
        Custom Property 1:
          description: Custom property 1 value.
          type: string
        Custom Property 2:
          description: Custom property 2 value.
          type: string
        Custom Property 3:
          description: Custom property 3 value.
          type: string
        Custom Property 4:
          description: Custom property 4 value.
          type: string
        Custom Property 5:
          description: Custom property 5 value.
          type: string
        Custom Property 6:
          description: Custom property 6 value.
          type: string
        Custom Property 7:
          description: Custom property 7 value.
          type: string
        Custom Property 8:
          description: Custom property 8 value.
          type: string
        Custom Property 9:
          description: Custom property 9 value.
          type: string
        Custom Property 10:
          description: Custom property 10 value.
          type: string
        Custom Property 11:
          description: Custom property 11 value.
          type: string
        Custom Property 12:
          description: Custom property 12 value.
          type: string
        Custom Property 13:
          description: Custom property 13 value.
          type: string
        Custom Property 14:
          description: Custom property 14 value.
          type: string
        Custom Property 15:
          description: Custom property 15 value.
          type: string
        Custom Property 16:
          description: Custom property 16 value.
          type: string
        Custom Property 17:
          description: Custom property 17 value.
          type: string
        Custom Property 18:
          description: Custom property 18 value.
          type: string
        Custom Property 19:
          description: Custom property 19 value.
          type: string
        Custom Property 20:
          description: Custom property 20 value.
          type: string
        customproperty21:
          description: Custom property 21 value.
          type: string
        customproperty22:
          description: Custom property 22 value.
          type: string
        customproperty23:
          description: Custom property 23 value.
          type: string
        customproperty24:
          description: Custom property 24 value.
          type: string
        customproperty25:
          description: Custom property 25 value.
          type: string
        customproperty26:
          description: Custom property 26 value.
          type: string
        customproperty27:
          description: Custom property 27 value.
          type: string
        customproperty28:
          description: Custom property 28 value.
          type: string
        customproperty29:
          description: Custom property 29 value.
          type: string
        customproperty30:
          description: Custom property 30 value.
          type: string
        customproperty31:
          description: Custom property 31 value.
          type: string
        customproperty32:
          description: Custom property 32 value.
          type: string
        customproperty33:
          description: Custom property 33 value.
          type: string
        customproperty34:
          description: Custom property 34 value.
          type: string
        customproperty35:
          description: Custom property 35 value.
          type: string
        customproperty36:
          description: Custom property 36 value.
          type: string
        customproperty37:
          description: Custom property 37 value.
          type: string
        customproperty38:
          description: Custom property 38 value.
          type: string
        customproperty39:
          description: Custom property 39 value.
          type: string
        customproperty40:
          description: Custom property 40 value.
          type: string
        Test Support:
          description: Test support property.
          example: cp3
          type: string
        accounts:
          description: List of accounts associated with the entitlement.
          items:
            $ref: "#/components/schemas/GetEntitlementResponse_Entitlementdetails_inner_accounts_inner"
          type: array
        entitlementMapDetails:
          description: List of mapped entitlement details.
          items:
            $ref: "#/components/schemas/GetEntitlementResponse_Entitlementdetails_inner_entitlementMapDetails_inner"
          type: array
    CreateOrUpdateEntitlementResponse_entitlementObj_entitlementOwner:
      example:
        Rank 200:
        - Saviynt_Training_User
        Rank 201:
        - Saviynt_Training_User
      oneOf:
      - description: Entitlement owner as a string.
        type: string
      - additionalProperties:
          items:
            type: string
        description: Entitlement owners organized by rank.
    CreateOrUpdateEntitlementResponse_entitlementObj:
      description: The created or updated entitlement object.
      example:
        customproperty10: customproperty10
        customproperty12: customproperty12
        customproperty11: customproperty11
        customproperty18: customproperty18
        customproperty17: customproperty17
        createdate: 2025-09-02 05:04:19
        customproperty19: customproperty19
        customproperty14: customproperty14
        customproperty13: customproperty13
        customproperty16: customproperty16
        customproperty15: customproperty15
        entitlement_glossary: hello
        updatedate: 2025-09-02 06:06:00
        entitlement_value: postman_ent_1
        customproperty40: customproperty40
        module: IT
        priviliged: "0"
        entitlementType: ui_ent_type_1
        priority: "23"
        soxcritical: "6"
        status: "6"
        customproperty4: customproperty4
        customproperty32: customproperty32
        customproperty5: customproperty5
        customproperty31: customproperty31
        customproperty2: customproperty2
        customproperty34: customproperty34
        access: Delete
        customproperty3: cp3
        customproperty33: customproperty33
        customproperty1: cp1
        customproperty30: customproperty30
        endpointKey: 25307
        confidentiality: "3"
        customproperty39: customproperty39
        description: description for postman_ent_1
        customproperty36: customproperty36
        customproperty35: customproperty35
        customproperty38: customproperty38
        customproperty37: customproperty37
        endpoint: sample-101
        customproperty8: customproperty8
        customproperty9: customproperty9
        customproperty6: customproperty6
        customproperty7: customproperty7
        customproperty21: cp21
        syscritical: "3"
        customproperty20: cp20
        customproperty23: customproperty23
        customproperty22: customproperty22
        entitlement_valuekey: "8609642"
        customproperty29: customproperty29
        customproperty28: customproperty28
        entitlementOwner:
          Rank 200:
          - Saviynt_Training_User
          Rank 201:
          - Saviynt_Training_User
        entitlementTypeName: ui_ent_type_1
        customproperty25: customproperty25
        customproperty24: customproperty24
        customproperty27: customproperty27
        customproperty26: customproperty26
        entitlementTypeKey: 28846
        requestForm: Request Form Table
        displayname: display name for postman_ent_1
        risk: "4"
        updateuser: "109809"
      properties:
        access:
          example: Delete
          type: string
        customproperty1:
          example: cp1
          type: string
        customproperty2:
          type: string
        customproperty3:
          example: cp3
          type: string
        customproperty4:
          type: string
        customproperty5:
          type: string
        customproperty6:
          type: string
        customproperty7:
          type: string
        customproperty8:
          type: string
        customproperty9:
          type: string
        customproperty10:
          type: string
        customproperty11:
          type: string
        customproperty12:
          type: string
        customproperty13:
          type: string
        customproperty14:
          type: string
        customproperty15:
          type: string
        customproperty16:
          type: string
        customproperty17:
          type: string
        customproperty18:
          type: string
        customproperty19:
          type: string
        customproperty20:
          example: cp20
          type: string
        customproperty21:
          example: cp21
          type: string
        customproperty22:
          type: string
        customproperty23:
          type: string
        customproperty24:
          type: string
        customproperty25:
          type: string
        customproperty26:
          type: string
        customproperty27:
          type: string
        customproperty28:
          type: string
        customproperty29:
          type: string
        customproperty30:
          type: string
        customproperty31:
          type: string
        customproperty32:
          type: string
        customproperty33:
          type: string
        customproperty34:
          type: string
        customproperty35:
          type: string
        customproperty36:
          type: string
        customproperty37:
          type: string
        customproperty38:
          type: string
        customproperty39:
          type: string
        customproperty40:
          type: string
        endpointKey:
          example: 25307
          type: integer
        confidentiality:
          example: "3"
          type: string
        createdate:
          example: 2025-09-02 05:04:19
          type: string
        description:
          example: description for postman_ent_1
          type: string
        entitlement_glossary:
          example: hello
          type: string
        endpoint:
          example: sample-101
          type: string
        updatedate:
          example: 2025-09-02 06:06:00
          type: string
        entitlement_value:
          example: postman_ent_1
          type: string
        syscritical:
          example: "3"
          type: string
        entitlement_valuekey:
          example: "8609642"
          type: string
        module:
          example: IT
          type: string
        entitlementOwner:
          $ref: "#/components/schemas/CreateOrUpdateEntitlementResponse_entitlementObj_entitlementOwner"
        priviliged:
          example: "0"
          type: string
        entitlementTypeName:
          example: ui_ent_type_1
          type: string
        entitlementType:
          example: ui_ent_type_1
          type: string
        priority:
          example: "23"
          type: string
        entitlementTypeKey:
          example: 28846
          type: integer
        requestForm:
          example: Request Form Table
          type: string
        displayname:
          example: display name for postman_ent_1
          type: string
        soxcritical:
          example: "6"
          type: string
        risk:
          example: "4"
          type: string
        status:
          example: "6"
          type: string
        updateuser:
          example: "109809"
          type: string
